### PR TITLE
Event refactoring

### PR DESCRIPTION
**Pull request by fairlight1337**

### CODE REVIEW

**Comment by fairlight1337** [comment]
@gaya- is this breaking anything for you?
I usually don'y fiddle around in the plan knowledge, but I needed to add some classes and some object assertion. The handling for `shape`-typed objects was `nil` before, so I assume I'm at least not breaking existing code :).

**Comment by gaya-** [comment]
I need to work on the proposal today. Can you wait until tomorrow evening or so? I can test it then.

**Comment by fairlight1337** [comment]
Sure, no problem :). Good luck on writing!

**Comment by gaya-** [comment]
Hey Jan, could you please try to do ``git pull --rebase origin master`` when you pull the updates in future? Because otherwise the merge commits from previous pull requests sneak into your pull requests and thus they contain unrelated changes.

**Comment by fairlight1337** [comment]
Okido, thanks

**Comment by gaya-** [comment]
If the rebase doesn't work without merging you can always do ``git rebase --abort`` I think (git will give you the suggestion, you've probably seen it before) and then do the usual ``git pull`` instead.

**Pull request merged**
