### PR TITLE
High Level plan fixes, addition of new task knowledge package, everyday activity plans

### PR DESCRIPTION
**Pull request by fairlight1337**

### CODE REVIEW

**Comment by fairlight1337** [comment]
Objections?

@airballking @gaya-

**Comment by gaya-** [comment]
You changed the object manipulation again. I'll have to test that.

**Comment by gaya-** [comment]
Hey Jan, could you please create a new branch each time you open a pull request so that the commits wouldn't stack onto each other? Or have two separate branches in your repo, one for PRs and one for after a PR is hanging but you continue developing. Otherwise they grow enormous. If my simulation is broken and you change something in the plan library I can't test it until I fix my simulation. And that can sometimes take long. Or, alternatively, create PRs much more often and one PR per feature / bug fix. I think that could make merging them much faster and easier. E.g., this PR was hanging because I had to check the changes in only 1 of the 13 files involved.
(Just a friendly request from a fellow developer to make the whole pull requests thing faster and more pleasant.)

**Comment by fairlight1337** [comment]
Hey,

Okay, I see your issue. Sorry for your trouble with my workflow. Opening multiple pull requests doesn't work as GitHub always references an always existing one when you create a new one and there is still one open. I usually always have a pull request open, as I issue them regularly.. but of course it's pretty time consuming to check them.

I'll see about the branch thing. Might actually be a good addition to the workflow to have a separate branch for pull requests. I'll think of something next time I have commits to pull request to the main repo.

Just curious: Which parts do break your simulation? Of course we all share a common code base that all of us are using (e.g., cram_designators). But which parts overlap between you and me that tend to break your stuff?

**Comment by gaya-** [comment]
We share everything except the process modules, you use ```cram_pr2```, I use ```pr2_projection_process_modules```. And the testing scenarios, of course. I didn't say that it's always your commits that get the simulation broken, I'm just saying that sometimes for whatever reason it is broken and I need time to fix it. The reasons are different, before the tf2 change it was the change to new Ubuntu and ROS, unfortunately I didn't get to fix everything that came with that and now it's all mixed up, before that it was knowrob, before that my personal refactoring, catkinization, whatever...

My impression is that the plan library is the most fragile part of the system, together with all the multithreading stuff. Projection uses asynchronous process modules, you use synchronous, which shouldn't matter but is still a difference. So, that's the part I'm most careful with.

It's a long discussion, we can talk about it in person some time...

**Comment by fairlight1337** [comment]
Talk about what?

**Pull request merged**
